### ISSUE TITLE
ros service to mqtt can't make it work

### ISSUE THREAD

**Issue by ggari-robotnik** [LCAS/mqtt_bridge#7]
@marc-hanheide, thanks for this awesome tool

I'm trying to expose a ros service through a mqtt broker using your bridge. I'm unable to do it. 

the ros-service-2-mqtt-broker side seems to be fine, I could see some activity on the mqtt-broker

On the local machine the service returns the following when is called:
```bash
rosservice call /rb1_base/image_provider/comm_enable "data: false" 
success: True
message: "Picture send disabled"
```

but I cannot make it work, when I do on the remote machine:

```bash
rosservice call /rb1_base/image_provider/comm_enable "data: false" 
```
or 
```bash
rosservice call /remote/image_provider/comm_enable "data: false" 
```
I won't get any response (I have ctrl+c the command)

The topics works really good with the same mqtt broker.

I use the following tag of the bridge
**mqtt_bridge tag:** 1.2.2

Server configuration yaml:
```yaml
---
mqtt:
  client:
    protocol: 4      # MQTTv311
  connection:
    host: $(arg mqtt_host)
    port: $(arg mqtt_port)
    keepalive: 60
  private_path: device/001
serializer: json:dumps
deserializer: json:loads
bridge:
  - factory: mqtt_bridge.bridge:DynamicBridgeServer
    control_topic: '__dynamic_server'
  - factory: mqtt_bridge.bridge:LocalServiceProxy
    control_topic: '__dynamic_server'
    local_server: /rb1_base/image_provider/comm_enable
    remote_server: /remote/image_provider/comm_enable
    srv_type: std_srvs.srv:SetBool

```

Remote configuration yaml:
```yaml
---
mqtt:
  client:
    protocol: 4      # MQTTv311
  connection:
    host: $(arg mqtt_host)
    port: $(arg mqtt_port)
    keepalive: 60
  private_path: device/001
serializer: json:dumps
deserializer: json:loads
bridge:
  - factory: mqtt_bridge.bridge:DynamicBridgeServer
    control_topic: '__dynamic_server'
  - factory: mqtt_bridge.bridge:RemoteService
    control_topic: '__dynamic_server'
    local_server: /rb1_base/image_provider/comm_enable
    remote_server: /remote/image_provider/comm_enable
    srv_type: std_srvs.srv:SetBool
```

on the mosquito broker I can the see the following:
```bash
mosquitto_sub -t '__dynamic_server/#' -d
Client mosq-0pRVZ6vcjoKjbbyO1T sending CONNECT
Client mosq-0pRVZ6vcjoKjbbyO1T received CONNACK (0)
Client mosq-0pRVZ6vcjoKjbbyO1T sending SUBSCRIBE (Mid: 1, Topic: __dynamic_server/#, QoS: 0, Options: 0x00)
Client mosq-0pRVZ6vcjoKjbbyO1T received SUBACK
Subscribed (mid: 1): 0
Client mosq-0pRVZ6vcjoKjbbyO1T received PUBLISH (d0, q0, r1, m0, '__dynamic_server/service/register/_rb1_base_image_provider_comm_enable_TO__remote_image_provider_comm_enable', ... (212 bytes))
{"args": {"local_server": "/remote/image_provider/comm_enable", "srv_type": "std_srvs.srv:SetBool", "remote_server": "/rb1_base/image_provider/comm_enable", "control_topic": "__dynamic_server"}, "op": "register"}
```
my remote node:
```bash
rosnode info /rb1_base/mqtt_bridge_test 
--------------------------------------------------------------------------------
Node [/rb1_base/mqtt_bridge_test]
Publications: 
 * /rosout [rosgraph_msgs/Log]

Subscriptions: None

Services: 
 * /rb1_base/image_provider/comm_enable
 * /rb1_base/mqtt_bridge_test/get_loggers
 * /rb1_base/mqtt_bridge_test/set_logger_level
 * /remote/image_provider/comm_enable


contacting node http://10.1.33.139:34737/ ...
Pid: 63
Connections:
 * topic: /rosout
    * to: /rosout
    * direction: outbound
    * transport: TCPROS
```

Can you help me with that?

Thanks in advance

**Comment by marc-hanheide** [comment]
This is likely just a configuration problem you are having. You don't want to configure the service on both side, but only at one. The respective other side is automatically taken care of by the `DynamicBridgeServer`.

So, I think you'd want to remove the `LocalServiceProxy` from the server config:
```yaml
---
mqtt:
  client:
    protocol: 4      # MQTTv311
  connection:
    host: $(arg mqtt_host)
    port: $(arg mqtt_port)
    keepalive: 60
  private_path: device/001
serializer: json:dumps
deserializer: json:loads
bridge:
  - factory: mqtt_bridge.bridge:DynamicBridgeServer
    control_topic: '__dynamic_server'
#  - factory: mqtt_bridge.bridge:LocalServiceProxy
#    control_topic: '__dynamic_server'
#    local_server: /rb1_base/image_provider/comm_enable
#    remote_server: /remote/image_provider/comm_enable
#    srv_type: std_srvs.srv:SetBool
```
